import type {
  Decision,
  Assumption,
  Simulation,
  Agent,
  AgentProposal,
  TeamMember,
  Document,
  ActivityItem,
  MetricCardData,
  User,
  Workspace,
  Notification,
  AuditLogEntry,
  Integration,
  BillingPlan,
  Invoice,
  UsageMetric,
  APIKey,
  SecurityEvent,
  ActiveSession,
} from "./types";

export const mockMetrics: MetricCardData[] = [
  { label: "Active Decisions", value: "47", change: 12.3, trend: "up", icon: "GitBranch" },
  { label: "Avg Decision Quality", value: "78.4", change: 4.2, trend: "up", icon: "Gauge" },
  { label: "Assumption Accuracy", value: "84.1%", change: -2.1, trend: "down", icon: "Target" },
  { label: "Strategic Confidence", value: "91.2", change: 6.8, trend: "up", icon: "ShieldCheck" },
];

export const mockDecisions: Decision[] = [
  {
    id: "dec-001",
    title: "Expand into European market via Berlin office",
    description: "Strategic expansion to establish European presence starting with Germany.",
    strategicIntent: "Growth",
    category: "Market Expansion",
    owner: { name: "Sarah Chen", type: "human", avatar: "SC" },
    status: "active",
    dqs: 87,
    diw: 9.2,
    assumptionCount: 6,
    createdAt: "2026-03-10T09:00:00Z",
    updatedAt: "2026-03-15T14:30:00Z",
  },
  {
    id: "dec-002",
    title: "Migrate core infrastructure to multi-cloud",
    description: "Reduce vendor lock-in and improve reliability with multi-cloud architecture.",
    strategicIntent: "Efficiency",
    category: "Infrastructure",
    owner: { name: "Marcus Rodriguez", type: "human", avatar: "MR" },
    status: "active",
    dqs: 72,
    diw: 8.5,
    assumptionCount: 8,
    createdAt: "2026-03-08T10:00:00Z",
    updatedAt: "2026-03-14T16:00:00Z",
  },
  {
    id: "dec-003",
    title: "Launch AI-assisted customer onboarding flow",
    description: "Automate and personalize the customer onboarding experience using AI.",
    strategicIntent: "Growth",
    category: "Product",
    owner: { name: "PricingAgent", type: "agent" },
    status: "active",
    dqs: 91,
    diw: 7.8,
    assumptionCount: 4,
    createdAt: "2026-03-05T08:00:00Z",
    updatedAt: "2026-03-13T11:00:00Z",
  },
  {
    id: "dec-004",
    title: "Consolidate vendor contracts for 20% cost reduction",
    description: "Renegotiate and consolidate SaaS vendor agreements to reduce operational costs.",
    strategicIntent: "Efficiency",
    category: "Operations",
    owner: { name: "David Park", type: "human", avatar: "DP" },
    status: "completed",
    dqs: 83,
    diw: 6.4,
    assumptionCount: 5,
    createdAt: "2026-02-20T09:00:00Z",
    updatedAt: "2026-03-12T10:00:00Z",
  },
  {
    id: "dec-005",
    title: "Implement zero-trust security architecture",
    description: "Transition to zero-trust model across all internal systems and APIs.",
    strategicIntent: "Defense",
    category: "Security",
    owner: { name: "Aisha Patel", type: "human", avatar: "AP" },
    status: "active",
    dqs: 76,
    diw: 9.5,
    assumptionCount: 7,
    createdAt: "2026-03-01T08:00:00Z",
    updatedAt: "2026-03-15T09:00:00Z",
  },
  {
    id: "dec-006",
    title: "Pilot predictive analytics for churn prevention",
    description: "Deploy ML models to identify and proactively address customer churn risk.",
    strategicIntent: "Experiment",
    category: "Data Science",
    owner: { name: "MarketingAgent", type: "agent", avatar: "MA" },
    status: "draft",
    dqs: 65,
    diw: 7.2,
    assumptionCount: 9,
    createdAt: "2026-03-14T10:00:00Z",
    updatedAt: "2026-03-15T15:00:00Z",
  },
  {
    id: "dec-007",
    title: "Restructure pricing tiers based on usage analytics",
    description: "Align pricing with actual value delivery using product usage data.",
    strategicIntent: "Growth",
    category: "Revenue",
    owner: { name: "Elena Vasquez", type: "human", avatar: "EV" },
    status: "active",
    dqs: 79,
    diw: 8.8,
    assumptionCount: 5,
    createdAt: "2026-03-07T09:00:00Z",
    updatedAt: "2026-03-14T13:00:00Z",
  },
  {
    id: "dec-008",
    title: "Establish strategic partnership with Databricks",
    description: "Create joint go-to-market offering combining decision intelligence with data lakehouse.",
    strategicIntent: "Growth",
    category: "Partnerships",
    owner: { name: "Sarah Chen", type: "human", avatar: "SC" },
    status: "active",
    dqs: 68,
    diw: 8.1,
    assumptionCount: 6,
    createdAt: "2026-03-09T11:00:00Z",
    updatedAt: "2026-03-15T16:00:00Z",
  },
  {
    id: "dec-009",
    title: "Deprecate legacy REST API v1 endpoints",
    description: "Sunset v1 API to reduce maintenance burden and security surface area.",
    strategicIntent: "Risk Mitigation",
    category: "Engineering",
    owner: { name: "Marcus Rodriguez", type: "human", avatar: "MR" },
    status: "completed",
    dqs: 94,
    diw: 5.6,
    assumptionCount: 3,
    createdAt: "2026-02-15T08:00:00Z",
    updatedAt: "2026-03-10T12:00:00Z",
  },
  {
    id: "dec-010",
    title: "Build compliance automation framework for SOC2",
    description: "Automate SOC2 compliance evidence collection and continuous monitoring.",
    strategicIntent: "Defense",
    category: "Compliance",
    owner: { name: "Aisha Patel", type: "human", avatar: "AP" },
    status: "active",
    dqs: 81,
    diw: 9.0,
    assumptionCount: 4,
    createdAt: "2026-03-03T09:00:00Z",
    updatedAt: "2026-03-15T08:00:00Z",
  },
  {
    id: "dec-011",
    title: "Introduce team-level decision review cadence",
    description: "Establish weekly decision review meetings to improve organizational decision quality.",
    strategicIntent: "Efficiency",
    category: "Process",
    owner: { name: "David Park", type: "human", avatar: "DP" },
    status: "draft",
    dqs: 58,
    diw: 6.0,
    assumptionCount: 3,
    createdAt: "2026-03-14T14:00:00Z",
    updatedAt: "2026-03-15T10:00:00Z",
  },
  {
    id: "dec-012",
    title: "Evaluate acquisition of InsightML startup",
    description: "Assess strategic fit and financial viability of acquiring InsightML for AI capabilities.",
    strategicIntent: "Growth",
    category: "M&A",
    owner: { name: "Elena Vasquez", type: "human", avatar: "EV" },
    status: "active",
    dqs: 62,
    diw: 9.8,
    assumptionCount: 11,
    createdAt: "2026-03-11T10:00:00Z",
    updatedAt: "2026-03-15T17:00:00Z",
  },
];

export const mockAssumptions: Assumption[] = [
  { id: "asm-001", text: "European regulatory environment will remain stable through Q4 2026", impactWeight: 5, status: "pending", decisionId: "dec-001", decisionTitle: "Expand into European market", owner: "Sarah Chen", updatedAt: "2026-03-15T10:00:00Z" },
  { id: "asm-002", text: "Berlin talent pool has sufficient senior engineering candidates", impactWeight: 4, status: "validated", decisionId: "dec-001", decisionTitle: "Expand into European market", owner: "Sarah Chen", updatedAt: "2026-03-14T09:00:00Z" },
  { id: "asm-003", text: "Office setup costs will not exceed $500K", impactWeight: 3, status: "validated", decisionId: "dec-001", decisionTitle: "Expand into European market", owner: "David Park", updatedAt: "2026-03-13T16:00:00Z" },
  { id: "asm-004", text: "Multi-cloud migration can be completed in 6 months", impactWeight: 5, status: "challenged", decisionId: "dec-002", decisionTitle: "Migrate to multi-cloud", owner: "Marcus Rodriguez", updatedAt: "2026-03-15T11:00:00Z" },
  { id: "asm-005", text: "AWS to GCP data transfer costs below $20K/month", impactWeight: 4, status: "pending", decisionId: "dec-002", decisionTitle: "Migrate to multi-cloud", owner: "Marcus Rodriguez", updatedAt: "2026-03-14T15:00:00Z" },
  { id: "asm-006", text: "Team has capacity for migration alongside feature work", impactWeight: 4, status: "challenged", decisionId: "dec-002", decisionTitle: "Migrate to multi-cloud", owner: "Marcus Rodriguez", updatedAt: "2026-03-15T08:00:00Z" },
  { id: "asm-007", text: "AI onboarding reduces time-to-value by 40%", impactWeight: 5, status: "pending", decisionId: "dec-003", decisionTitle: "AI-assisted onboarding", owner: "PricingAgent", updatedAt: "2026-03-13T14:00:00Z" },
  { id: "asm-008", text: "Customer satisfaction improves with AI-guided flows", impactWeight: 3, status: "validated", decisionId: "dec-003", decisionTitle: "AI-assisted onboarding", owner: "PricingAgent", updatedAt: "2026-03-12T11:00:00Z" },
  { id: "asm-009", text: "Vendor consolidation savings offset switching costs within 6 months", impactWeight: 4, status: "validated", decisionId: "dec-004", decisionTitle: "Consolidate vendor contracts", owner: "David Park", updatedAt: "2026-03-10T09:00:00Z" },
  { id: "asm-010", text: "No critical feature gaps in consolidated vendor stack", impactWeight: 5, status: "validated", decisionId: "dec-004", decisionTitle: "Consolidate vendor contracts", owner: "David Park", updatedAt: "2026-03-09T14:00:00Z" },
  { id: "asm-011", text: "Zero-trust implementation won't impact developer velocity", impactWeight: 4, status: "challenged", decisionId: "dec-005", decisionTitle: "Zero-trust security", owner: "Aisha Patel", updatedAt: "2026-03-15T09:30:00Z" },
  { id: "asm-012", text: "Existing SSO infrastructure is compatible with zero-trust model", impactWeight: 3, status: "validated", decisionId: "dec-005", decisionTitle: "Zero-trust security", owner: "Aisha Patel", updatedAt: "2026-03-11T10:00:00Z" },
  { id: "asm-013", text: "Churn prediction model achieves >80% accuracy on historical data", impactWeight: 5, status: "pending", decisionId: "dec-006", decisionTitle: "Predictive analytics for churn", owner: "MarketingAgent", updatedAt: "2026-03-15T14:00:00Z" },
  { id: "asm-014", text: "Sales team willing to adopt AI-recommended interventions", impactWeight: 4, status: "pending", decisionId: "dec-006", decisionTitle: "Predictive analytics for churn", owner: "MarketingAgent", updatedAt: "2026-03-14T16:00:00Z" },
  { id: "asm-015", text: "Usage-based pricing aligns with customer perception of value", impactWeight: 5, status: "pending", decisionId: "dec-007", decisionTitle: "Restructure pricing tiers", owner: "Elena Vasquez", updatedAt: "2026-03-14T12:00:00Z" },
  { id: "asm-016", text: "Pricing change will not increase churn above 3%", impactWeight: 5, status: "pending", decisionId: "dec-007", decisionTitle: "Restructure pricing tiers", owner: "Elena Vasquez", updatedAt: "2026-03-13T15:00:00Z" },
  { id: "asm-017", text: "Databricks partnership adds $2M ARR in 12 months", impactWeight: 4, status: "pending", decisionId: "dec-008", decisionTitle: "Strategic partnership with Databricks", owner: "Sarah Chen", updatedAt: "2026-03-15T11:00:00Z" },
  { id: "asm-018", text: "Joint customers see 2x faster time-to-insight", impactWeight: 3, status: "pending", decisionId: "dec-008", decisionTitle: "Strategic partnership with Databricks", owner: "Sarah Chen", updatedAt: "2026-03-14T10:00:00Z" },
  { id: "asm-019", text: "Less than 5% of active users depend on v1 API endpoints", impactWeight: 4, status: "validated", decisionId: "dec-009", decisionTitle: "Deprecate legacy REST API", owner: "Marcus Rodriguez", updatedAt: "2026-03-08T09:00:00Z" },
  { id: "asm-020", text: "Migration tooling covers 95% of v1 to v2 patterns", impactWeight: 3, status: "validated", decisionId: "dec-009", decisionTitle: "Deprecate legacy REST API", owner: "Marcus Rodriguez", updatedAt: "2026-03-07T14:00:00Z" },
  { id: "asm-021", text: "SOC2 automation reduces audit prep time by 70%", impactWeight: 4, status: "pending", decisionId: "dec-010", decisionTitle: "SOC2 compliance automation", owner: "Aisha Patel", updatedAt: "2026-03-15T08:30:00Z" },
  { id: "asm-022", text: "InsightML technology is compatible with our architecture", impactWeight: 5, status: "pending", decisionId: "dec-012", decisionTitle: "Evaluate InsightML acquisition", owner: "Elena Vasquez", updatedAt: "2026-03-15T16:00:00Z" },
  { id: "asm-023", text: "InsightML team retention rate will be above 80% post-acquisition", impactWeight: 5, status: "challenged", decisionId: "dec-012", decisionTitle: "Evaluate InsightML acquisition", owner: "Elena Vasquez", updatedAt: "2026-03-15T12:00:00Z" },
  { id: "asm-024", text: "Acquisition costs recoverable within 18 months via revenue synergies", impactWeight: 4, status: "pending", decisionId: "dec-012", decisionTitle: "Evaluate InsightML acquisition", owner: "David Park", updatedAt: "2026-03-14T17:00:00Z" },
];

export const mockSimulations: Simulation[] = [
  { id: "sim-001", title: "European Market Entry Scenarios", description: "Model outcomes for Berlin office expansion across economic conditions.", probability: 0.72, status: "completed", outcomeCount: 4, linkedDecisions: 2, createdAt: "2026-03-10T09:00:00Z", updatedAt: "2026-03-14T12:00:00Z" },
  { id: "sim-002", title: "Multi-Cloud Cost Projection", description: "Compare infrastructure costs across cloud providers over 24 months.", probability: 0.85, status: "completed", outcomeCount: 3, linkedDecisions: 1, createdAt: "2026-03-08T10:00:00Z", updatedAt: "2026-03-13T16:00:00Z" },
  { id: "sim-003", title: "Pricing Restructure Impact", description: "Simulate revenue impact of usage-based pricing across customer segments.", probability: 0.64, status: "running", outcomeCount: 5, linkedDecisions: 2, createdAt: "2026-03-12T09:00:00Z", updatedAt: "2026-03-15T10:00:00Z" },
  { id: "sim-004", title: "Churn Intervention Effectiveness", description: "Model the impact of AI-recommended interventions on customer retention.", probability: 0.58, status: "running", outcomeCount: 3, linkedDecisions: 1, createdAt: "2026-03-14T08:00:00Z", updatedAt: "2026-03-15T14:00:00Z" },
  { id: "sim-005", title: "InsightML Acquisition Scenarios", description: "Financial and strategic outcome modeling for InsightML acquisition.", probability: 0.51, status: "draft", outcomeCount: 6, linkedDecisions: 3, createdAt: "2026-03-15T09:00:00Z", updatedAt: "2026-03-15T16:00:00Z" },
  { id: "sim-006", title: "Security Architecture Migration Risk", description: "Assess operational risk during zero-trust architecture transition.", probability: 0.78, status: "completed", outcomeCount: 3, linkedDecisions: 1, createdAt: "2026-03-05T09:00:00Z", updatedAt: "2026-03-12T11:00:00Z" },
];

export const mockAgents: Agent[] = [
  {
    id: "agt-001",
    name: "PricingAgent",
    role: "Pricing Optimization",
    department: "Revenue",
    objective: "Maximize revenue while minimizing churn through data-driven pricing decisions",
    status: "active",
    capabilities: ["Adjust pricing tiers", "Propose discount campaigns", "Analyze price elasticity"],
    decisionScope: ["pricing"],
    riskBoundaries: { maxDiscountPercent: 25, maxSpendThreshold: 50000, allowIrreversible: false },
    instructionLayer: "You are a pricing optimization agent. Your goal is to maximize revenue while minimizing churn. Always justify decisions using historical performance.",
    pendingProposals: 2,
    forecastAccuracy: 81,
    dqsScore: 8.4,
    roiContribution: "$2.4M",
    riskExposure: "medium",
    failureRate: 12,
    successRate: 67,
    decisionsProcessed: 34,
    lastActive: "2026-03-15T15:30:00Z",
  },
  {
    id: "agt-002",
    name: "MarketingAgent",
    role: "Campaign Intelligence",
    department: "Marketing",
    objective: "Optimize campaign timing and spend using pattern recognition and historical outcomes",
    status: "active",
    capabilities: ["Propose campaign strategies", "Adjust ad spend", "Analyze conversion patterns"],
    decisionScope: ["campaigns"],
    riskBoundaries: { maxSpendThreshold: 25000, allowIrreversible: false },
    instructionLayer: "You are a marketing intelligence agent. Optimize campaign timing and budget allocation. Reference past campaign outcomes before proposing new ones.",
    pendingProposals: 1,
    forecastAccuracy: 78,
    dqsScore: 7.6,
    roiContribution: "$1.1M",
    riskExposure: "low",
    failureRate: 18,
    successRate: 61,
    decisionsProcessed: 22,
    lastActive: "2026-03-15T14:45:00Z",
  },
  {
    id: "agt-003",
    name: "SalesAgent",
    role: "Pipeline Optimization",
    department: "Sales",
    objective: "Optimize sales pipeline and contract strategies to maximize close rates",
    status: "active",
    capabilities: ["Analyze pipeline health", "Propose contract terms", "Flag at-risk deals"],
    decisionScope: ["sales", "pricing"],
    riskBoundaries: { maxDiscountPercent: 15, maxSpendThreshold: 100000, allowIrreversible: false },
    instructionLayer: "You are a sales pipeline agent. Your goal is to maximize close rates and deal value. Escalate any contract deviation beyond approved thresholds.",
    pendingProposals: 3,
    forecastAccuracy: 85,
    dqsScore: 8.1,
    roiContribution: "$3.2M",
    riskExposure: "medium",
    failureRate: 15,
    successRate: 72,
    decisionsProcessed: 48,
    lastActive: "2026-03-15T16:00:00Z",
  },
  {
    id: "agt-004",
    name: "OpsAgent",
    role: "Process Optimization",
    department: "Operations",
    objective: "Identify operational inefficiencies and propose process improvements",
    status: "active",
    capabilities: ["Analyze workflow bottlenecks", "Propose vendor changes", "Optimize resource allocation"],
    decisionScope: ["operations"],
    riskBoundaries: { maxSpendThreshold: 30000, allowIrreversible: false },
    instructionLayer: "You are an operations optimization agent. Reduce waste and improve throughput. Always validate proposed changes against historical operational data.",
    pendingProposals: 0,
    forecastAccuracy: 83,
    dqsScore: 7.9,
    roiContribution: "$890K",
    riskExposure: "low",
    failureRate: 10,
    successRate: 74,
    decisionsProcessed: 31,
    lastActive: "2026-03-15T13:20:00Z",
  },
  {
    id: "agt-005",
    name: "SecurityAgent",
    role: "Risk Assessment",
    department: "Security",
    objective: "Monitor security posture and flag risk patterns before they become incidents",
    status: "paused",
    capabilities: ["Monitor API patterns", "Flag anomalies", "Recommend security controls"],
    decisionScope: ["security", "operations"],
    riskBoundaries: { allowIrreversible: false },
    instructionLayer: "You are a security risk agent. Detect and flag risk patterns proactively. Never auto-approve actions that affect production security posture.",
    pendingProposals: 0,
    forecastAccuracy: 91,
    dqsScore: 9.0,
    roiContribution: "$420K",
    riskExposure: "low",
    failureRate: 5,
    successRate: 88,
    decisionsProcessed: 56,
    lastActive: "2026-03-14T18:00:00Z",
  },
];

export const mockAgentProposals: AgentProposal[] = [
  {
    id: "prop-001", agentId: "agt-001", agentName: "PricingAgent",
    title: "Launch 15% Q4 discount campaign",
    intent: "Increase Q4 revenue through targeted discounting on mid-tier plans",
    description: "Historical data shows 15% discounts on mid-tier yielded 23% conversion lift in Q3. Proposing equivalent Q4 campaign.",
    assumptions: ["Mid-tier price sensitivity remains consistent from Q3", "Competitor pricing stays stable through Q4"],
    expectedOutcomes: ["Projected 18-25% conversion lift", "Estimated $340K incremental revenue"],
    riskLevel: "medium",
    confidenceScore: 79,
    type: "decision", priority: "high", createdAt: "2026-03-15T14:00:00Z",
  },
  {
    id: "prop-002", agentId: "agt-003", agentName: "SalesAgent",
    title: "Reduce enterprise contract floor to $8k/yr",
    intent: "Lower entry barrier for mid-market enterprise deals to increase pipeline volume",
    description: "Pipeline analysis shows 34% of stalled deals cite minimum contract as blocker. Propose reducing floor from $12k to $8k.",
    assumptions: ["Stalled deals will reactivate at lower floor", "Margin remains viable at $8k threshold"],
    expectedOutcomes: ["Reactivate 12-15 stalled deals", "Increase pipeline velocity by 20%"],
    riskLevel: "high",
    confidenceScore: 65,
    type: "decision", priority: "high", createdAt: "2026-03-15T15:30:00Z",
  },
  {
    id: "prop-003", agentId: "agt-002", agentName: "MarketingAgent",
    title: "Increase paid ad spend by $12k for product launch",
    intent: "Capitalize on product launch momentum with accelerated paid acquisition",
    description: "Launch week historically shows 3.2x ROAS. Propose $12k incremental spend across Google and LinkedIn.",
    assumptions: ["Launch week ROAS aligns with historical 3.2x average", "LinkedIn CPL remains below $45"],
    expectedOutcomes: ["Generate 260+ qualified leads", "Achieve 2.8x minimum ROAS"],
    riskLevel: "low",
    confidenceScore: 84,
    type: "decision", priority: "medium", createdAt: "2026-03-15T12:00:00Z",
  },
  {
    id: "prop-004", agentId: "agt-004", agentName: "OpsAgent",
    title: "Consolidate vendor stack from 8 to 5 tools",
    intent: "Reduce operational overhead and costs through vendor consolidation",
    description: "3 overlapping tools identified with redundant capabilities. Consolidation saves $4,200/mo without feature loss.",
    assumptions: ["No critical feature gaps in consolidated stack", "Migration completes within 2 sprint cycles"],
    expectedOutcomes: ["$50K annual savings", "Reduced integration maintenance by 40%"],
    riskLevel: "low",
    confidenceScore: 88,
    type: "decision", priority: "medium", createdAt: "2026-03-15T11:00:00Z",
  },
  {
    id: "prop-005", agentId: "agt-002", agentName: "MarketingAgent",
    title: "Simulate Q2 campaign budget allocation scenarios",
    intent: "Model optimal budget distribution across channels before Q2 planning",
    description: "Q1 channel performance data available. Propose simulation across 4 allocation strategies.",
    assumptions: ["Q1 channel performance is predictive of Q2", "No major platform algorithm changes expected"],
    expectedOutcomes: ["Identify optimal allocation strategy", "Reduce budget waste by 15-20%"],
    riskLevel: "low",
    confidenceScore: 91,
    type: "simulation", priority: "low", createdAt: "2026-03-15T10:00:00Z",
  },
  {
    id: "prop-006", agentId: "agt-001", agentName: "PricingAgent",
    title: "Challenge assumption on enterprise price elasticity",
    intent: "Update pricing model with new elasticity data from Q1 renewals",
    description: "Q1 renewal data shows enterprise segment is less price-sensitive than modeled. Current assumption may be overly conservative.",
    assumptions: ["Q1 renewal data is representative of broader enterprise segment"],
    expectedOutcomes: ["More accurate pricing model", "Potential 8-12% revenue uplift from adjusted pricing"],
    riskLevel: "low",
    confidenceScore: 76,
    type: "assumption", priority: "medium", createdAt: "2026-03-15T09:00:00Z",
  },
];

export const mockTeamMembers: TeamMember[] = [
  { id: "tm-001", name: "Sarah Chen", email: "sarah@stemmq.com", role: "Chief Strategy Officer", avatar: "SC", forecastReliability: 91, lastActive: "2026-03-15T16:00:00Z" },
  { id: "tm-002", name: "Marcus Rodriguez", email: "marcus@stemmq.com", role: "VP Engineering", avatar: "MR", forecastReliability: 84, lastActive: "2026-03-15T15:30:00Z" },
  { id: "tm-003", name: "Aisha Patel", email: "aisha@stemmq.com", role: "Head of Security", avatar: "AP", forecastReliability: 88, lastActive: "2026-03-15T14:45:00Z" },
  { id: "tm-004", name: "David Park", email: "david@stemmq.com", role: "Director of Operations", avatar: "DP", forecastReliability: 79, lastActive: "2026-03-15T13:00:00Z" },
  { id: "tm-005", name: "Elena Vasquez", email: "elena@stemmq.com", role: "Head of Product", avatar: "EV", forecastReliability: 86, lastActive: "2026-03-15T16:30:00Z" },
  { id: "tm-006", name: "James Liu", email: "james@stemmq.com", role: "Senior Data Scientist", avatar: "JL", forecastReliability: 92, lastActive: "2026-03-15T12:00:00Z" },
  { id: "tm-007", name: "Priya Sharma", email: "priya@stemmq.com", role: "Product Designer", avatar: "PS", forecastReliability: 77, lastActive: "2026-03-14T18:00:00Z" },
  { id: "tm-008", name: "Tom Williams", email: "tom@stemmq.com", role: "Solutions Architect", avatar: "TW", forecastReliability: 81, lastActive: "2026-03-15T11:00:00Z" },
  { id: "tm-009", name: "Nina Kowalski", email: "nina@stemmq.com", role: "Customer Success Lead", avatar: "NK", forecastReliability: 85, lastActive: "2026-03-15T15:00:00Z" },
  { id: "tm-010", name: "Alex Thompson", email: "alex@stemmq.com", role: "Engineering Manager", avatar: "AT", forecastReliability: 83, lastActive: "2026-03-15T14:00:00Z" },
];

export const mockDocuments: Document[] = [
  { id: "doc-001", name: "Q1 2026 Strategic Plan.pdf", type: "PDF", size: "4.2 MB", uploadedBy: "Sarah Chen", uploadedAt: "2026-03-01T09:00:00Z", processingStatus: "processed", linkedDecisions: 5 },
  { id: "doc-002", name: "Market Analysis - Europe.docx", type: "DOCX", size: "2.8 MB", uploadedBy: "Elena Vasquez", uploadedAt: "2026-03-05T10:00:00Z", processingStatus: "processed", linkedDecisions: 2 },
  { id: "doc-003", name: "Infrastructure Migration Plan.pptx", type: "PPTX", size: "8.1 MB", uploadedBy: "Marcus Rodriguez", uploadedAt: "2026-03-08T14:00:00Z", processingStatus: "processed", linkedDecisions: 3 },
  { id: "doc-004", name: "Security Audit Report 2026.pdf", type: "PDF", size: "1.5 MB", uploadedBy: "Aisha Patel", uploadedAt: "2026-03-10T09:00:00Z", processingStatus: "processed", linkedDecisions: 2 },
  { id: "doc-005", name: "Customer Churn Analysis.xlsx", type: "XLSX", size: "3.6 MB", uploadedBy: "James Liu", uploadedAt: "2026-03-12T11:00:00Z", processingStatus: "processing", linkedDecisions: 1 },
  { id: "doc-006", name: "Pricing Research Summary.pdf", type: "PDF", size: "956 KB", uploadedBy: "Elena Vasquez", uploadedAt: "2026-03-13T15:00:00Z", processingStatus: "processed", linkedDecisions: 1 },
  { id: "doc-007", name: "InsightML Due Diligence.pdf", type: "PDF", size: "12.4 MB", uploadedBy: "David Park", uploadedAt: "2026-03-14T09:00:00Z", processingStatus: "processing", linkedDecisions: 1 },
  { id: "doc-008", name: "SOC2 Compliance Checklist.xlsx", type: "XLSX", size: "1.1 MB", uploadedBy: "Aisha Patel", uploadedAt: "2026-03-14T14:00:00Z", processingStatus: "processed", linkedDecisions: 1 },
  { id: "doc-009", name: "Board Presentation Q1.pptx", type: "PPTX", size: "15.2 MB", uploadedBy: "Sarah Chen", uploadedAt: "2026-03-15T08:00:00Z", processingStatus: "queued", linkedDecisions: 0 },
  { id: "doc-010", name: "Vendor Comparison Matrix.csv", type: "CSV", size: "245 KB", uploadedBy: "David Park", uploadedAt: "2026-03-15T10:00:00Z", processingStatus: "processed", linkedDecisions: 2 },
];

export const mockActivityFeed: ActivityItem[] = [
  { id: "act-001", user: "Sarah Chen", avatar: "SC", action: "updated", target: "Expand into European market", targetType: "decision", timestamp: "2026-03-15T16:30:00Z" },
  { id: "act-002", user: "SalesAgent", avatar: "SA", action: "proposed", target: "Reduce enterprise contract floor to $8k/yr", targetType: "decision", timestamp: "2026-03-15T16:00:00Z" },
  { id: "act-003", user: "Elena Vasquez", avatar: "EV", action: "created", target: "InsightML Acquisition Scenarios", targetType: "simulation", timestamp: "2026-03-15T15:30:00Z" },
  { id: "act-004", user: "PricingAgent", avatar: "PA", action: "proposed", target: "Launch 15% Q4 discount campaign", targetType: "decision", timestamp: "2026-03-15T14:00:00Z" },
  { id: "act-005", user: "Marcus Rodriguez", avatar: "MR", action: "challenged", target: "Multi-cloud migration timeline", targetType: "assumption", timestamp: "2026-03-15T13:30:00Z" },
  { id: "act-006", user: "Aisha Patel", avatar: "AP", action: "uploaded", target: "SOC2 Compliance Checklist.xlsx", targetType: "document", timestamp: "2026-03-15T13:00:00Z" },
  { id: "act-007", user: "David Park", avatar: "DP", action: "validated", target: "Vendor consolidation savings assumption", targetType: "assumption", timestamp: "2026-03-15T12:00:00Z" },
  { id: "act-008", user: "MarketingAgent", avatar: "MA", action: "completed", target: "Q2 campaign budget allocation simulation", targetType: "simulation", timestamp: "2026-03-15T11:30:00Z" },
  { id: "act-009", user: "James Liu", avatar: "JL", action: "uploaded", target: "Customer Churn Analysis.xlsx", targetType: "document", timestamp: "2026-03-15T11:00:00Z" },
  { id: "act-010", user: "Elena Vasquez", avatar: "EV", action: "updated", target: "Restructure pricing tiers", targetType: "decision", timestamp: "2026-03-15T10:30:00Z" },
  { id: "act-011", user: "Sarah Chen", avatar: "SC", action: "invited", target: "Alex Thompson", targetType: "team", timestamp: "2026-03-15T10:00:00Z" },
  { id: "act-012", user: "OpsAgent", avatar: "OA", action: "proposed", target: "Consolidate vendor stack from 8 to 5 tools", targetType: "decision", timestamp: "2026-03-15T09:30:00Z" },
  { id: "act-013", user: "Priya Sharma", avatar: "PS", action: "created", target: "Dashboard redesign proposal", targetType: "decision", timestamp: "2026-03-15T09:00:00Z" },
  { id: "act-014", user: "Marcus Rodriguez", avatar: "MR", action: "validated", target: "API v1 usage below 5%", targetType: "assumption", timestamp: "2026-03-14T18:00:00Z" },
  { id: "act-015", user: "Aisha Patel", avatar: "AP", action: "created", target: "SOC2 compliance automation", targetType: "decision", timestamp: "2026-03-14T17:00:00Z" },
];

// ============================================
// Extended mock data for new pages
// ============================================

export const mockUser: User = {
  id: "usr-001",
  name: "Sarah Chen",
  email: "sarah@stemmq.com",
  avatar: "SC",
  role: "Chief Strategy Officer",
  company: "StemmQ",
  workspaceId: "ws-001",
  onboardingCompleted: true,
};

export const mockWorkspaces: Workspace[] = [
  { id: "ws-001", name: "StemmQ HQ", slug: "stemmq-hq", memberCount: 10, plan: "professional" },
  { id: "ws-002", name: "StemmQ Labs", slug: "stemmq-labs", memberCount: 4, plan: "starter" },
  { id: "ws-003", name: "StemmQ Enterprise", slug: "stemmq-enterprise", memberCount: 48, plan: "enterprise" },
];

export const mockNotifications: Notification[] = [
  { id: "notif-001", title: "New proposal from PricingAgent", message: "PricingAgent proposed launching a 15% Q4 discount campaign.", type: "update", read: false, actionUrl: "/agents", createdAt: "2026-03-16T09:00:00Z", actor: { name: "PricingAgent", avatar: "PA" } },
  { id: "notif-002", title: "Assumption challenged", message: "Marcus Rodriguez challenged the multi-cloud migration timeline assumption.", type: "warning", read: false, actionUrl: "/assumptions", createdAt: "2026-03-16T08:30:00Z", actor: { name: "Marcus Rodriguez", avatar: "MR" } },
  { id: "notif-003", title: "Simulation completed", message: "European Market Entry Scenarios simulation has finished running.", type: "success", read: false, actionUrl: "/simulations", createdAt: "2026-03-16T08:00:00Z" },
  { id: "notif-004", title: "You were mentioned", message: "Elena Vasquez mentioned you in a comment on 'Restructure pricing tiers'.", type: "mention", read: false, actionUrl: "/decisions", createdAt: "2026-03-15T17:00:00Z", actor: { name: "Elena Vasquez", avatar: "EV" } },
  { id: "notif-005", title: "Decision escalated", message: "SalesAgent proposal to reduce contract floor exceeded risk threshold — requires approval.", type: "error", read: true, actionUrl: "/agents", createdAt: "2026-03-15T15:30:00Z", actor: { name: "SalesAgent", avatar: "SA" } },
  { id: "notif-006", title: "Document processed", message: "InsightML Due Diligence.pdf has been processed successfully.", type: "info", read: true, actionUrl: "/documents", createdAt: "2026-03-15T14:00:00Z" },
  { id: "notif-007", title: "Team member joined", message: "Alex Thompson has accepted the invitation and joined the team.", type: "success", read: true, createdAt: "2026-03-15T10:00:00Z", actor: { name: "Alex Thompson", avatar: "AT" } },
  { id: "notif-008", title: "Weekly decision review", message: "Your weekly decision quality report is ready for review.", type: "info", read: true, actionUrl: "/analytics", createdAt: "2026-03-14T09:00:00Z" },
];

export const mockAuditLogs: AuditLogEntry[] = [
  { id: "audit-001", action: "decision.updated", actor: "Sarah Chen", actorAvatar: "SC", resource: "Expand into European market", resourceType: "decision", details: "Updated strategic intent from Defense to Growth", ipAddress: "192.168.1.42", timestamp: "2026-03-16T09:15:00Z" },
  { id: "audit-002", action: "assumption.challenged", actor: "Marcus Rodriguez", actorAvatar: "MR", resource: "Multi-cloud migration timeline", resourceType: "assumption", details: "Changed status from pending to challenged", ipAddress: "192.168.1.105", timestamp: "2026-03-16T08:45:00Z" },
  { id: "audit-003", action: "agent.decision_proposed", actor: "PricingAgent", actorAvatar: "PA", resource: "Launch 15% Q4 discount campaign", resourceType: "agent", details: "Structured decision object generated — confidence 79%, risk medium", ipAddress: "10.0.0.1", timestamp: "2026-03-16T08:30:00Z" },
  { id: "audit-004", action: "document.uploaded", actor: "Aisha Patel", actorAvatar: "AP", resource: "SOC2 Compliance Checklist.xlsx", resourceType: "document", details: "Uploaded new compliance document (1.1 MB)", ipAddress: "192.168.1.78", timestamp: "2026-03-15T14:00:00Z" },
  { id: "audit-005", action: "team.member_invited", actor: "Sarah Chen", actorAvatar: "SC", resource: "Alex Thompson", resourceType: "team", details: "Invited alex@stemmq.com with Engineering Manager role", ipAddress: "192.168.1.42", timestamp: "2026-03-15T10:00:00Z" },
  { id: "audit-006", action: "simulation.started", actor: "Elena Vasquez", actorAvatar: "EV", resource: "Pricing Restructure Impact", resourceType: "simulation", details: "Started Monte Carlo simulation with 10,000 iterations", ipAddress: "192.168.1.92", timestamp: "2026-03-15T09:30:00Z" },
  { id: "audit-007", action: "settings.updated", actor: "Sarah Chen", actorAvatar: "SC", resource: "Organization settings", resourceType: "settings", details: "Updated decision review cadence to weekly", ipAddress: "192.168.1.42", timestamp: "2026-03-14T16:00:00Z" },
  { id: "audit-008", action: "auth.login", actor: "David Park", actorAvatar: "DP", resource: "Session", resourceType: "auth", details: "Logged in via Google OAuth", ipAddress: "192.168.1.55", timestamp: "2026-03-14T09:00:00Z" },
];

export const mockIntegrations: Integration[] = [
  { id: "int-001", name: "Salesforce", description: "Sync decisions with CRM pipeline data and customer outcomes.", icon: "Database", category: "crm", status: "connected", connectedAt: "2026-02-15T10:00:00Z" },
  { id: "int-002", name: "Slack", description: "Get real-time notifications and updates in your Slack workspace.", icon: "MessageSquare", category: "communication", status: "connected", connectedAt: "2026-01-20T09:00:00Z" },
  { id: "int-003", name: "Jira", description: "Link decisions to development epics and track implementation.", icon: "SquareKanban", category: "project", status: "available" },
  { id: "int-004", name: "HubSpot", description: "Connect marketing and sales data to validate growth assumptions.", icon: "Database", category: "crm", status: "available" },
  { id: "int-005", name: "Notion", description: "Sync decision documentation and strategy wikis.", icon: "BookOpen", category: "project", status: "available" },
  { id: "int-006", name: "GitHub", description: "Link technical decisions to code changes and PRs.", icon: "Github", category: "project", status: "available" },
  { id: "int-007", name: "Google Analytics", description: "Import web analytics to validate product decisions.", icon: "BarChart3", category: "analytics", status: "coming_soon" },
  { id: "int-008", name: "Snowflake", description: "Connect to your data warehouse for advanced analytics.", icon: "Database", category: "analytics", status: "coming_soon" },
  { id: "int-009", name: "Google Drive", description: "Import documents directly from Google Drive.", icon: "FolderOpen", category: "storage", status: "available" },
  { id: "int-010", name: "OpenAI", description: "Enhanced AI capabilities for decision analysis.", icon: "Brain", category: "ai", status: "coming_soon" },
];

export const mockBillingData: BillingPlan = {
  name: "Professional",
  price: 149,
  interval: "monthly",
  features: [
    "Up to 50 team members",
    "Unlimited decisions",
    "AI-powered simulations",
    "Agent decision governance",
    "Priority support",
  ],
  usage: {
    decisions: { used: 47, limit: -1 },
    members: { used: 10, limit: 50 },
    storage: { used: 2.4, limit: 10, unit: "GB" },
    apiCalls: { used: 12450, limit: 50000 },
  },
};

export const mockInvoices: Invoice[] = [
  { id: "inv-001", date: "2026-03-01", amount: 149, status: "paid", downloadUrl: "#" },
  { id: "inv-002", date: "2026-02-01", amount: 149, status: "paid", downloadUrl: "#" },
  { id: "inv-003", date: "2026-01-01", amount: 149, status: "paid", downloadUrl: "#" },
  { id: "inv-004", date: "2025-12-01", amount: 119, status: "paid", downloadUrl: "#" },
  { id: "inv-005", date: "2025-11-01", amount: 119, status: "paid", downloadUrl: "#" },
];

export const mockUsageMetrics: UsageMetric[] = [
  {
    label: "Decisions Created",
    total: 47,
    change: 12.3,
    data: [
      { date: "2026-03-10", value: 3 }, { date: "2026-03-11", value: 5 },
      { date: "2026-03-12", value: 4 }, { date: "2026-03-13", value: 6 },
      { date: "2026-03-14", value: 8 }, { date: "2026-03-15", value: 7 },
      { date: "2026-03-16", value: 2 },
    ],
  },
  {
    label: "API Calls",
    total: 12450,
    change: 8.7,
    data: [
      { date: "2026-03-10", value: 1820 }, { date: "2026-03-11", value: 2100 },
      { date: "2026-03-12", value: 1950 }, { date: "2026-03-13", value: 2300 },
      { date: "2026-03-14", value: 2400 }, { date: "2026-03-15", value: 1880 },
      { date: "2026-03-16", value: 980 },
    ],
  },
  {
    label: "Simulations Run",
    total: 24,
    change: 15.2,
    data: [
      { date: "2026-03-10", value: 2 }, { date: "2026-03-11", value: 4 },
      { date: "2026-03-12", value: 3 }, { date: "2026-03-13", value: 5 },
      { date: "2026-03-14", value: 4 }, { date: "2026-03-15", value: 3 },
      { date: "2026-03-16", value: 1 },
    ],
  },
  {
    label: "Team Activity",
    total: 156,
    change: -2.4,
    data: [
      { date: "2026-03-10", value: 22 }, { date: "2026-03-11", value: 28 },
      { date: "2026-03-12", value: 25 }, { date: "2026-03-13", value: 30 },
      { date: "2026-03-14", value: 24 }, { date: "2026-03-15", value: 18 },
      { date: "2026-03-16", value: 9 },
    ],
  },
];

export const mockAPIKeys: APIKey[] = [
  { id: "key-001", name: "Production API", key: "sk_live_xxxxxxxxxxxxxxxxxxxx_a8Kd", prefix: "sk_live_", createdAt: "2026-01-15T10:00:00Z", lastUsed: "2026-03-16T08:30:00Z", expiresAt: null, permissions: ["read", "write", "admin"] },
  { id: "key-002", name: "Development API", key: "sk_test_xxxxxxxxxxxxxxxxxxxx_j2Lm", prefix: "sk_test_", createdAt: "2026-02-01T09:00:00Z", lastUsed: "2026-03-15T17:00:00Z", expiresAt: "2026-06-01T00:00:00Z", permissions: ["read", "write"] },
  { id: "key-003", name: "CI/CD Pipeline", key: "sk_live_xxxxxxxxxxxxxxxxxxxx_p4Nq", prefix: "sk_live_", createdAt: "2026-02-20T14:00:00Z", lastUsed: "2026-03-16T06:00:00Z", expiresAt: null, permissions: ["read"] },
  { id: "key-004", name: "Analytics Dashboard", key: "sk_test_xxxxxxxxxxxxxxxxxxxx_r7Ws", prefix: "sk_test_", createdAt: "2026-03-05T11:00:00Z", lastUsed: null, expiresAt: "2026-09-05T00:00:00Z", permissions: ["read"] },
];

export const mockSecurityEvents: SecurityEvent[] = [
  { id: "sec-001", type: "login", description: "Signed in with Google OAuth", ipAddress: "192.168.1.42", device: "Chrome on macOS", location: "San Francisco, CA", timestamp: "2026-03-16T08:00:00Z" },
  { id: "sec-002", type: "api_key_created", description: "Created API key: Analytics Dashboard", ipAddress: "192.168.1.42", device: "Chrome on macOS", location: "San Francisco, CA", timestamp: "2026-03-05T11:00:00Z" },
  { id: "sec-003", type: "password_change", description: "Password changed successfully", ipAddress: "192.168.1.42", device: "Chrome on macOS", location: "San Francisco, CA", timestamp: "2026-02-28T14:00:00Z" },
  { id: "sec-004", type: "2fa_enabled", description: "Two-factor authentication enabled", ipAddress: "192.168.1.42", device: "Chrome on macOS", location: "San Francisco, CA", timestamp: "2026-02-15T10:00:00Z" },
  { id: "sec-005", type: "login", description: "Signed in with email and password", ipAddress: "10.0.0.55", device: "Safari on iOS", location: "San Francisco, CA", timestamp: "2026-03-14T09:00:00Z" },
  { id: "sec-006", type: "session_revoked", description: "Revoked session on Firefox", ipAddress: "192.168.1.42", device: "Chrome on macOS", location: "San Francisco, CA", timestamp: "2026-03-10T16:00:00Z" },
];

export const mockActiveSessions: ActiveSession[] = [
  { id: "sess-001", device: "macOS", browser: "Chrome 122", location: "San Francisco, CA", ipAddress: "192.168.1.42", lastActive: "2026-03-16T09:00:00Z", current: true },
  { id: "sess-002", device: "iOS", browser: "Safari", location: "San Francisco, CA", ipAddress: "10.0.0.55", lastActive: "2026-03-15T18:00:00Z", current: false },
  { id: "sess-003", device: "Windows", browser: "Edge 122", location: "New York, NY", ipAddress: "172.16.0.12", lastActive: "2026-03-14T12:00:00Z", current: false },
];
