import type {
  Decision,
  Assumption,
  Simulation,
  Agent,
  AgentProposal,
  TeamMember,
  Document,
  ActivityItem,
  MetricCardData,
} from "./types";

export const mockMetrics: MetricCardData[] = [
  { label: "Active Decisions", value: "47", change: 12.3, trend: "up", icon: "GitBranch" },
  { label: "Avg Decision Quality", value: "78.4", change: 4.2, trend: "up", icon: "Gauge" },
  { label: "Assumption Accuracy", value: "84.1%", change: -2.1, trend: "down", icon: "Target" },
  { label: "Strategic Confidence", value: "91.2", change: 6.8, trend: "up", icon: "ShieldCheck" },
];

export const mockDecisions: Decision[] = [
  {
    id: "dec-001",
    title: "Expand into European market via Berlin office",
    description: "Strategic expansion to establish European presence starting with Germany.",
    strategicIntent: "Growth",
    category: "Market Expansion",
    owner: { name: "Sarah Chen", type: "human", avatar: "SC" },
    status: "active",
    dqs: 87,
    diw: 9.2,
    assumptionCount: 6,
    createdAt: "2026-03-10T09:00:00Z",
    updatedAt: "2026-03-15T14:30:00Z",
  },
  {
    id: "dec-002",
    title: "Migrate core infrastructure to multi-cloud",
    description: "Reduce vendor lock-in and improve reliability with multi-cloud architecture.",
    strategicIntent: "Efficiency",
    category: "Infrastructure",
    owner: { name: "Marcus Rodriguez", type: "human", avatar: "MR" },
    status: "active",
    dqs: 72,
    diw: 8.5,
    assumptionCount: 8,
    createdAt: "2026-03-08T10:00:00Z",
    updatedAt: "2026-03-14T16:00:00Z",
  },
  {
    id: "dec-003",
    title: "Launch AI-assisted customer onboarding flow",
    description: "Automate and personalize the customer onboarding experience using AI.",
    strategicIntent: "Growth",
    category: "Product",
    owner: { name: "Agent Aria", type: "agent" },
    status: "active",
    dqs: 91,
    diw: 7.8,
    assumptionCount: 4,
    createdAt: "2026-03-05T08:00:00Z",
    updatedAt: "2026-03-13T11:00:00Z",
  },
  {
    id: "dec-004",
    title: "Consolidate vendor contracts for 20% cost reduction",
    description: "Renegotiate and consolidate SaaS vendor agreements to reduce operational costs.",
    strategicIntent: "Efficiency",
    category: "Operations",
    owner: { name: "David Park", type: "human", avatar: "DP" },
    status: "completed",
    dqs: 83,
    diw: 6.4,
    assumptionCount: 5,
    createdAt: "2026-02-20T09:00:00Z",
    updatedAt: "2026-03-12T10:00:00Z",
  },
  {
    id: "dec-005",
    title: "Implement zero-trust security architecture",
    description: "Transition to zero-trust model across all internal systems and APIs.",
    strategicIntent: "Defense",
    category: "Security",
    owner: { name: "Aisha Patel", type: "human", avatar: "AP" },
    status: "active",
    dqs: 76,
    diw: 9.5,
    assumptionCount: 7,
    createdAt: "2026-03-01T08:00:00Z",
    updatedAt: "2026-03-15T09:00:00Z",
  },
  {
    id: "dec-006",
    title: "Pilot predictive analytics for churn prevention",
    description: "Deploy ML models to identify and proactively address customer churn risk.",
    strategicIntent: "Experiment",
    category: "Data Science",
    owner: { name: "Agent Nova", type: "agent" },
    status: "draft",
    dqs: 65,
    diw: 7.2,
    assumptionCount: 9,
    createdAt: "2026-03-14T10:00:00Z",
    updatedAt: "2026-03-15T15:00:00Z",
  },
  {
    id: "dec-007",
    title: "Restructure pricing tiers based on usage analytics",
    description: "Align pricing with actual value delivery using product usage data.",
    strategicIntent: "Growth",
    category: "Revenue",
    owner: { name: "Elena Vasquez", type: "human", avatar: "EV" },
    status: "active",
    dqs: 79,
    diw: 8.8,
    assumptionCount: 5,
    createdAt: "2026-03-07T09:00:00Z",
    updatedAt: "2026-03-14T13:00:00Z",
  },
  {
    id: "dec-008",
    title: "Establish strategic partnership with Databricks",
    description: "Create joint go-to-market offering combining decision intelligence with data lakehouse.",
    strategicIntent: "Growth",
    category: "Partnerships",
    owner: { name: "Sarah Chen", type: "human", avatar: "SC" },
    status: "active",
    dqs: 68,
    diw: 8.1,
    assumptionCount: 6,
    createdAt: "2026-03-09T11:00:00Z",
    updatedAt: "2026-03-15T16:00:00Z",
  },
  {
    id: "dec-009",
    title: "Deprecate legacy REST API v1 endpoints",
    description: "Sunset v1 API to reduce maintenance burden and security surface area.",
    strategicIntent: "Risk Mitigation",
    category: "Engineering",
    owner: { name: "Marcus Rodriguez", type: "human", avatar: "MR" },
    status: "completed",
    dqs: 94,
    diw: 5.6,
    assumptionCount: 3,
    createdAt: "2026-02-15T08:00:00Z",
    updatedAt: "2026-03-10T12:00:00Z",
  },
  {
    id: "dec-010",
    title: "Build compliance automation framework for SOC2",
    description: "Automate SOC2 compliance evidence collection and continuous monitoring.",
    strategicIntent: "Defense",
    category: "Compliance",
    owner: { name: "Aisha Patel", type: "human", avatar: "AP" },
    status: "active",
    dqs: 81,
    diw: 9.0,
    assumptionCount: 4,
    createdAt: "2026-03-03T09:00:00Z",
    updatedAt: "2026-03-15T08:00:00Z",
  },
  {
    id: "dec-011",
    title: "Introduce team-level decision review cadence",
    description: "Establish weekly decision review meetings to improve organizational decision quality.",
    strategicIntent: "Efficiency",
    category: "Process",
    owner: { name: "David Park", type: "human", avatar: "DP" },
    status: "draft",
    dqs: 58,
    diw: 6.0,
    assumptionCount: 3,
    createdAt: "2026-03-14T14:00:00Z",
    updatedAt: "2026-03-15T10:00:00Z",
  },
  {
    id: "dec-012",
    title: "Evaluate acquisition of InsightML startup",
    description: "Assess strategic fit and financial viability of acquiring InsightML for AI capabilities.",
    strategicIntent: "Growth",
    category: "M&A",
    owner: { name: "Elena Vasquez", type: "human", avatar: "EV" },
    status: "active",
    dqs: 62,
    diw: 9.8,
    assumptionCount: 11,
    createdAt: "2026-03-11T10:00:00Z",
    updatedAt: "2026-03-15T17:00:00Z",
  },
];

export const mockAssumptions: Assumption[] = [
  { id: "asm-001", text: "European regulatory environment will remain stable through Q4 2026", impactWeight: 5, status: "pending", decisionId: "dec-001", decisionTitle: "Expand into European market", owner: "Sarah Chen", updatedAt: "2026-03-15T10:00:00Z" },
  { id: "asm-002", text: "Berlin talent pool has sufficient senior engineering candidates", impactWeight: 4, status: "validated", decisionId: "dec-001", decisionTitle: "Expand into European market", owner: "Sarah Chen", updatedAt: "2026-03-14T09:00:00Z" },
  { id: "asm-003", text: "Office setup costs will not exceed $500K", impactWeight: 3, status: "validated", decisionId: "dec-001", decisionTitle: "Expand into European market", owner: "David Park", updatedAt: "2026-03-13T16:00:00Z" },
  { id: "asm-004", text: "Multi-cloud migration can be completed in 6 months", impactWeight: 5, status: "challenged", decisionId: "dec-002", decisionTitle: "Migrate to multi-cloud", owner: "Marcus Rodriguez", updatedAt: "2026-03-15T11:00:00Z" },
  { id: "asm-005", text: "AWS to GCP data transfer costs below $20K/month", impactWeight: 4, status: "pending", decisionId: "dec-002", decisionTitle: "Migrate to multi-cloud", owner: "Marcus Rodriguez", updatedAt: "2026-03-14T15:00:00Z" },
  { id: "asm-006", text: "Team has capacity for migration alongside feature work", impactWeight: 4, status: "challenged", decisionId: "dec-002", decisionTitle: "Migrate to multi-cloud", owner: "Marcus Rodriguez", updatedAt: "2026-03-15T08:00:00Z" },
  { id: "asm-007", text: "AI onboarding reduces time-to-value by 40%", impactWeight: 5, status: "pending", decisionId: "dec-003", decisionTitle: "AI-assisted onboarding", owner: "Agent Aria", updatedAt: "2026-03-13T14:00:00Z" },
  { id: "asm-008", text: "Customer satisfaction improves with AI-guided flows", impactWeight: 3, status: "validated", decisionId: "dec-003", decisionTitle: "AI-assisted onboarding", owner: "Agent Aria", updatedAt: "2026-03-12T11:00:00Z" },
  { id: "asm-009", text: "Vendor consolidation savings offset switching costs within 6 months", impactWeight: 4, status: "validated", decisionId: "dec-004", decisionTitle: "Consolidate vendor contracts", owner: "David Park", updatedAt: "2026-03-10T09:00:00Z" },
  { id: "asm-010", text: "No critical feature gaps in consolidated vendor stack", impactWeight: 5, status: "validated", decisionId: "dec-004", decisionTitle: "Consolidate vendor contracts", owner: "David Park", updatedAt: "2026-03-09T14:00:00Z" },
  { id: "asm-011", text: "Zero-trust implementation won't impact developer velocity", impactWeight: 4, status: "challenged", decisionId: "dec-005", decisionTitle: "Zero-trust security", owner: "Aisha Patel", updatedAt: "2026-03-15T09:30:00Z" },
  { id: "asm-012", text: "Existing SSO infrastructure is compatible with zero-trust model", impactWeight: 3, status: "validated", decisionId: "dec-005", decisionTitle: "Zero-trust security", owner: "Aisha Patel", updatedAt: "2026-03-11T10:00:00Z" },
  { id: "asm-013", text: "Churn prediction model achieves >80% accuracy on historical data", impactWeight: 5, status: "pending", decisionId: "dec-006", decisionTitle: "Predictive analytics for churn", owner: "Agent Nova", updatedAt: "2026-03-15T14:00:00Z" },
  { id: "asm-014", text: "Sales team willing to adopt AI-recommended interventions", impactWeight: 4, status: "pending", decisionId: "dec-006", decisionTitle: "Predictive analytics for churn", owner: "Agent Nova", updatedAt: "2026-03-14T16:00:00Z" },
  { id: "asm-015", text: "Usage-based pricing aligns with customer perception of value", impactWeight: 5, status: "pending", decisionId: "dec-007", decisionTitle: "Restructure pricing tiers", owner: "Elena Vasquez", updatedAt: "2026-03-14T12:00:00Z" },
  { id: "asm-016", text: "Pricing change will not increase churn above 3%", impactWeight: 5, status: "pending", decisionId: "dec-007", decisionTitle: "Restructure pricing tiers", owner: "Elena Vasquez", updatedAt: "2026-03-13T15:00:00Z" },
  { id: "asm-017", text: "Databricks partnership adds $2M ARR in 12 months", impactWeight: 4, status: "pending", decisionId: "dec-008", decisionTitle: "Strategic partnership with Databricks", owner: "Sarah Chen", updatedAt: "2026-03-15T11:00:00Z" },
  { id: "asm-018", text: "Joint customers see 2x faster time-to-insight", impactWeight: 3, status: "pending", decisionId: "dec-008", decisionTitle: "Strategic partnership with Databricks", owner: "Sarah Chen", updatedAt: "2026-03-14T10:00:00Z" },
  { id: "asm-019", text: "Less than 5% of active users depend on v1 API endpoints", impactWeight: 4, status: "validated", decisionId: "dec-009", decisionTitle: "Deprecate legacy REST API", owner: "Marcus Rodriguez", updatedAt: "2026-03-08T09:00:00Z" },
  { id: "asm-020", text: "Migration tooling covers 95% of v1 to v2 patterns", impactWeight: 3, status: "validated", decisionId: "dec-009", decisionTitle: "Deprecate legacy REST API", owner: "Marcus Rodriguez", updatedAt: "2026-03-07T14:00:00Z" },
  { id: "asm-021", text: "SOC2 automation reduces audit prep time by 70%", impactWeight: 4, status: "pending", decisionId: "dec-010", decisionTitle: "SOC2 compliance automation", owner: "Aisha Patel", updatedAt: "2026-03-15T08:30:00Z" },
  { id: "asm-022", text: "InsightML technology is compatible with our architecture", impactWeight: 5, status: "pending", decisionId: "dec-012", decisionTitle: "Evaluate InsightML acquisition", owner: "Elena Vasquez", updatedAt: "2026-03-15T16:00:00Z" },
  { id: "asm-023", text: "InsightML team retention rate will be above 80% post-acquisition", impactWeight: 5, status: "challenged", decisionId: "dec-012", decisionTitle: "Evaluate InsightML acquisition", owner: "Elena Vasquez", updatedAt: "2026-03-15T12:00:00Z" },
  { id: "asm-024", text: "Acquisition costs recoverable within 18 months via revenue synergies", impactWeight: 4, status: "pending", decisionId: "dec-012", decisionTitle: "Evaluate InsightML acquisition", owner: "David Park", updatedAt: "2026-03-14T17:00:00Z" },
];

export const mockSimulations: Simulation[] = [
  { id: "sim-001", title: "European Market Entry Scenarios", description: "Model outcomes for Berlin office expansion across economic conditions.", probability: 0.72, status: "completed", outcomeCount: 4, linkedDecisions: 2, createdAt: "2026-03-10T09:00:00Z", updatedAt: "2026-03-14T12:00:00Z" },
  { id: "sim-002", title: "Multi-Cloud Cost Projection", description: "Compare infrastructure costs across cloud providers over 24 months.", probability: 0.85, status: "completed", outcomeCount: 3, linkedDecisions: 1, createdAt: "2026-03-08T10:00:00Z", updatedAt: "2026-03-13T16:00:00Z" },
  { id: "sim-003", title: "Pricing Restructure Impact", description: "Simulate revenue impact of usage-based pricing across customer segments.", probability: 0.64, status: "running", outcomeCount: 5, linkedDecisions: 2, createdAt: "2026-03-12T09:00:00Z", updatedAt: "2026-03-15T10:00:00Z" },
  { id: "sim-004", title: "Churn Intervention Effectiveness", description: "Model the impact of AI-recommended interventions on customer retention.", probability: 0.58, status: "running", outcomeCount: 3, linkedDecisions: 1, createdAt: "2026-03-14T08:00:00Z", updatedAt: "2026-03-15T14:00:00Z" },
  { id: "sim-005", title: "InsightML Acquisition Scenarios", description: "Financial and strategic outcome modeling for InsightML acquisition.", probability: 0.51, status: "draft", outcomeCount: 6, linkedDecisions: 3, createdAt: "2026-03-15T09:00:00Z", updatedAt: "2026-03-15T16:00:00Z" },
  { id: "sim-006", title: "Security Architecture Migration Risk", description: "Assess operational risk during zero-trust architecture transition.", probability: 0.78, status: "completed", outcomeCount: 3, linkedDecisions: 1, createdAt: "2026-03-05T09:00:00Z", updatedAt: "2026-03-12T11:00:00Z" },
];

export const mockAgents: Agent[] = [
  { id: "agt-001", name: "Agent Aria", objective: "Customer success and onboarding optimization", status: "active", pendingProposals: 2, accuracyScore: 92, decisionsProcessed: 34, lastActive: "2026-03-15T15:30:00Z" },
  { id: "agt-002", name: "Agent Nova", objective: "Predictive analytics and churn prevention", status: "active", pendingProposals: 1, accuracyScore: 87, decisionsProcessed: 18, lastActive: "2026-03-15T14:45:00Z" },
  { id: "agt-003", name: "Agent Sentinel", objective: "Security monitoring and risk assessment", status: "reviewing", pendingProposals: 3, accuracyScore: 95, decisionsProcessed: 56, lastActive: "2026-03-15T16:00:00Z" },
  { id: "agt-004", name: "Agent Compass", objective: "Market intelligence and competitive analysis", status: "active", pendingProposals: 0, accuracyScore: 83, decisionsProcessed: 22, lastActive: "2026-03-15T13:20:00Z" },
  { id: "agt-005", name: "Agent Forge", objective: "Engineering productivity and technical debt analysis", status: "paused", pendingProposals: 0, accuracyScore: 89, decisionsProcessed: 41, lastActive: "2026-03-14T18:00:00Z" },
];

export const mockAgentProposals: AgentProposal[] = [
  { id: "prop-001", agentId: "agt-001", agentName: "Agent Aria", title: "Reduce onboarding steps from 7 to 4", description: "Analysis shows steps 3, 5, and 6 have 60% drop-off. Propose consolidation.", type: "decision", priority: "high", createdAt: "2026-03-15T14:00:00Z" },
  { id: "prop-002", agentId: "agt-003", agentName: "Agent Sentinel", title: "Flag elevated API abuse pattern", description: "Detected 340% increase in rate-limited requests from 3 IP ranges. Recommend investigation.", type: "assumption", priority: "high", createdAt: "2026-03-15T15:30:00Z" },
  { id: "prop-003", agentId: "agt-001", agentName: "Agent Aria", title: "A/B test personalized welcome sequences", description: "Propose experiment with 3 personalization strategies for new enterprise customers.", type: "decision", priority: "medium", createdAt: "2026-03-15T12:00:00Z" },
  { id: "prop-004", agentId: "agt-003", agentName: "Agent Sentinel", title: "Update assumption on SSO compatibility", description: "New evidence suggests SAML 2.0 limitations with zero-trust scope. Challenge assumption asm-012.", type: "assumption", priority: "medium", createdAt: "2026-03-15T11:00:00Z" },
  { id: "prop-005", agentId: "agt-002", agentName: "Agent Nova", title: "Run churn simulation with Q1 data refresh", description: "Q1 2026 customer data available. Propose refreshing churn model with updated features.", type: "simulation", priority: "low", createdAt: "2026-03-15T10:00:00Z" },
  { id: "prop-006", agentId: "agt-003", agentName: "Agent Sentinel", title: "Recommend SOC2 evidence automation scope expansion", description: "3 additional controls can be automated based on current infrastructure maturity.", type: "decision", priority: "medium", createdAt: "2026-03-15T09:00:00Z" },
];

export const mockTeamMembers: TeamMember[] = [
  { id: "tm-001", name: "Sarah Chen", email: "sarah@stemmq.com", role: "Chief Strategy Officer", avatar: "SC", forecastReliability: 91, lastActive: "2026-03-15T16:00:00Z" },
  { id: "tm-002", name: "Marcus Rodriguez", email: "marcus@stemmq.com", role: "VP Engineering", avatar: "MR", forecastReliability: 84, lastActive: "2026-03-15T15:30:00Z" },
  { id: "tm-003", name: "Aisha Patel", email: "aisha@stemmq.com", role: "Head of Security", avatar: "AP", forecastReliability: 88, lastActive: "2026-03-15T14:45:00Z" },
  { id: "tm-004", name: "David Park", email: "david@stemmq.com", role: "Director of Operations", avatar: "DP", forecastReliability: 79, lastActive: "2026-03-15T13:00:00Z" },
  { id: "tm-005", name: "Elena Vasquez", email: "elena@stemmq.com", role: "Head of Product", avatar: "EV", forecastReliability: 86, lastActive: "2026-03-15T16:30:00Z" },
  { id: "tm-006", name: "James Liu", email: "james@stemmq.com", role: "Senior Data Scientist", avatar: "JL", forecastReliability: 92, lastActive: "2026-03-15T12:00:00Z" },
  { id: "tm-007", name: "Priya Sharma", email: "priya@stemmq.com", role: "Product Designer", avatar: "PS", forecastReliability: 77, lastActive: "2026-03-14T18:00:00Z" },
  { id: "tm-008", name: "Tom Williams", email: "tom@stemmq.com", role: "Solutions Architect", avatar: "TW", forecastReliability: 81, lastActive: "2026-03-15T11:00:00Z" },
  { id: "tm-009", name: "Nina Kowalski", email: "nina@stemmq.com", role: "Customer Success Lead", avatar: "NK", forecastReliability: 85, lastActive: "2026-03-15T15:00:00Z" },
  { id: "tm-010", name: "Alex Thompson", email: "alex@stemmq.com", role: "Engineering Manager", avatar: "AT", forecastReliability: 83, lastActive: "2026-03-15T14:00:00Z" },
];

export const mockDocuments: Document[] = [
  { id: "doc-001", name: "Q1 2026 Strategic Plan.pdf", type: "PDF", size: "4.2 MB", uploadedBy: "Sarah Chen", uploadedAt: "2026-03-01T09:00:00Z", processingStatus: "processed", linkedDecisions: 5 },
  { id: "doc-002", name: "Market Analysis - Europe.docx", type: "DOCX", size: "2.8 MB", uploadedBy: "Elena Vasquez", uploadedAt: "2026-03-05T10:00:00Z", processingStatus: "processed", linkedDecisions: 2 },
  { id: "doc-003", name: "Infrastructure Migration Plan.pptx", type: "PPTX", size: "8.1 MB", uploadedBy: "Marcus Rodriguez", uploadedAt: "2026-03-08T14:00:00Z", processingStatus: "processed", linkedDecisions: 3 },
  { id: "doc-004", name: "Security Audit Report 2026.pdf", type: "PDF", size: "1.5 MB", uploadedBy: "Aisha Patel", uploadedAt: "2026-03-10T09:00:00Z", processingStatus: "processed", linkedDecisions: 2 },
  { id: "doc-005", name: "Customer Churn Analysis.xlsx", type: "XLSX", size: "3.6 MB", uploadedBy: "James Liu", uploadedAt: "2026-03-12T11:00:00Z", processingStatus: "processing", linkedDecisions: 1 },
  { id: "doc-006", name: "Pricing Research Summary.pdf", type: "PDF", size: "956 KB", uploadedBy: "Elena Vasquez", uploadedAt: "2026-03-13T15:00:00Z", processingStatus: "processed", linkedDecisions: 1 },
  { id: "doc-007", name: "InsightML Due Diligence.pdf", type: "PDF", size: "12.4 MB", uploadedBy: "David Park", uploadedAt: "2026-03-14T09:00:00Z", processingStatus: "processing", linkedDecisions: 1 },
  { id: "doc-008", name: "SOC2 Compliance Checklist.xlsx", type: "XLSX", size: "1.1 MB", uploadedBy: "Aisha Patel", uploadedAt: "2026-03-14T14:00:00Z", processingStatus: "processed", linkedDecisions: 1 },
  { id: "doc-009", name: "Board Presentation Q1.pptx", type: "PPTX", size: "15.2 MB", uploadedBy: "Sarah Chen", uploadedAt: "2026-03-15T08:00:00Z", processingStatus: "queued", linkedDecisions: 0 },
  { id: "doc-010", name: "Vendor Comparison Matrix.csv", type: "CSV", size: "245 KB", uploadedBy: "David Park", uploadedAt: "2026-03-15T10:00:00Z", processingStatus: "processed", linkedDecisions: 2 },
];

export const mockActivityFeed: ActivityItem[] = [
  { id: "act-001", user: "Sarah Chen", avatar: "SC", action: "updated", target: "Expand into European market", targetType: "decision", timestamp: "2026-03-15T16:30:00Z" },
  { id: "act-002", user: "Agent Sentinel", avatar: "AS", action: "flagged", target: "SSO compatibility assumption", targetType: "assumption", timestamp: "2026-03-15T16:00:00Z" },
  { id: "act-003", user: "Elena Vasquez", avatar: "EV", action: "created", target: "InsightML Acquisition Scenarios", targetType: "simulation", timestamp: "2026-03-15T15:30:00Z" },
  { id: "act-004", user: "Agent Aria", avatar: "AA", action: "proposed", target: "Reduce onboarding steps from 7 to 4", targetType: "decision", timestamp: "2026-03-15T14:00:00Z" },
  { id: "act-005", user: "Marcus Rodriguez", avatar: "MR", action: "challenged", target: "Multi-cloud migration timeline", targetType: "assumption", timestamp: "2026-03-15T13:30:00Z" },
  { id: "act-006", user: "Aisha Patel", avatar: "AP", action: "uploaded", target: "SOC2 Compliance Checklist.xlsx", targetType: "document", timestamp: "2026-03-15T13:00:00Z" },
  { id: "act-007", user: "David Park", avatar: "DP", action: "validated", target: "Vendor consolidation savings assumption", targetType: "assumption", timestamp: "2026-03-15T12:00:00Z" },
  { id: "act-008", user: "Agent Nova", avatar: "AN", action: "completed", target: "Churn Intervention Effectiveness simulation", targetType: "simulation", timestamp: "2026-03-15T11:30:00Z" },
  { id: "act-009", user: "James Liu", avatar: "JL", action: "uploaded", target: "Customer Churn Analysis.xlsx", targetType: "document", timestamp: "2026-03-15T11:00:00Z" },
  { id: "act-010", user: "Elena Vasquez", avatar: "EV", action: "updated", target: "Restructure pricing tiers", targetType: "decision", timestamp: "2026-03-15T10:30:00Z" },
  { id: "act-011", user: "Sarah Chen", avatar: "SC", action: "invited", target: "Alex Thompson", targetType: "team", timestamp: "2026-03-15T10:00:00Z" },
  { id: "act-012", user: "Agent Compass", avatar: "AC", action: "analyzed", target: "Competitive landscape Q1 report", targetType: "document", timestamp: "2026-03-15T09:30:00Z" },
  { id: "act-013", user: "Priya Sharma", avatar: "PS", action: "created", target: "Dashboard redesign proposal", targetType: "decision", timestamp: "2026-03-15T09:00:00Z" },
  { id: "act-014", user: "Marcus Rodriguez", avatar: "MR", action: "validated", target: "API v1 usage below 5%", targetType: "assumption", timestamp: "2026-03-14T18:00:00Z" },
  { id: "act-015", user: "Aisha Patel", avatar: "AP", action: "created", target: "SOC2 compliance automation", targetType: "decision", timestamp: "2026-03-14T17:00:00Z" },
];
